baseurl = "https://robhorrigan.github.io/blog/"
languageCode = "en-US"

builddrafts = false
canonifyurls = true

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Arthur Dent"
title = "Arthur Dent"

pygmentsuseclasses = true
disqusShortname = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
Author = "Arthur Dent"
CacheBuster = true
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Description = "Don't panic"
Email = "you@example.space"
FaviconFile = "img/favicon.ico"
GATracker = "XYZ"
GitHub = "//github.com/you"
HighlightJS = true
Initials = "ad" # Displayed on single post page; DEPRECATED in v0.3.0.
Lang = "en"
LinkedIn = "//linkedin.com/in/you"
Twitter = "//twitter.com/you"
ExtraCssFiles = [ "/css/override.css" ] # In your `static/css`, add/remove files as necessary.
