baseurl = "https://robhorrigan.github.io/blog/"
title = "Blog of Rob Horrigan"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Rob Horrigan"
googleAnalytics = "XXX"
disqusShortname = "XXX"

[Author]
    name = "Rob Horrigan"
    profile = "https://robhorrigan.github.io/blog"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Welcome"
    description = "More to come shortly..."
    github = "https://github.com/robhorrigan"
    linkedin = "https://linkedin.com/in/roberthorrigan/"
    twitter = "https://twitter.com/rob_horrigan"
    stackoverflow = "http://stackoverflow.com/users/XXX/YYY"
    opengraph = true

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
